### ISSUE TITLE
error: could not find repository

### ISSUE THREAD

**Issue by nspyke** [getsentry/action-release#113]
# Github Sentry Action Release Bug Report

## Environment

How do you use this action?
Standard Github runners, ubuntu-22.04

Which version of the action?
v1

## Steps to Reproduce

```yaml
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: traqly
          SENTRY_PROJECT: web-app
        with:
          environment: staging
          version: ${{ github.sha }}
          ignore_empty: true
          ignore_missing: true
```

## Expected Result

No error.

## Actual Result

Command failed: /action-release/dist/sentry-cli releases set-commits 530d1864bdc32406a79b409e609a9836f32e80f2 --auto --ignore-missing --ignore-empty
error: could not find repository from '.'; class=Repository (6); code=NotFound (-3)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

It was working earlier this evening at around 0600 UTC, but now at 0900 UTC it's no longer working
