### ISSUE TITLE
Update `v1` tag to latest release

### ISSUE THREAD

**Issue by jcarvalho** [getsentry/action-release#114]
Hi.

Just noticed that version 1.2.1 is out, but the `v1` tag is still pointing at version 1.1.6.

Is this tag not officially supported (and thus we should explicitly specify the version), or is 1.2.1 not yet ready for use?

**Comment by armenzg** [comment]
We're making everyone follow the `v1` tag rather than have a tag per version.

**Comment by jcarvalho** [comment]
In that case, could we get the tag updated to point to the latest release, or is it not yet ready for Production use?

**Comment by armenzg** [comment]
Thanks for pointing that out. I am still becoming familiar with the release process of this.

@mattgauntseo-sentry I believe we need to tag the latest changeset for the change to be live.

Is pushing this tag change all it takes?

```
git tag -f v1
Updated tag 'v1' (was 744e4b2)
git show
commit bd5f874fcda966ba48139b0140fb3ec0cb3aabdd (HEAD -> master, tag: v1.2.1, tag: v1, origin/master, origin/HEAD)
Author: Matt Gaunt-Seo @ Sentry.io <112419115+mattgauntseo-sentry@users.noreply.github.com>
Date:   Thu Nov 3 12:32:59 2022 -0700

    Update version to 1.2.1 (#112)

diff --git a/package.json b/package.json
index 8b80fba..8295d1e 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "action-release",
-  "version": "1.2.0",
+  "version": "1.2.1",
   "private": true,
   "description": "GitHub Action for creating a release on Sentry",
   "main": "dist/index.js",
```

**Comment by mattgauntseo-sentry** [comment]
Ah apologies, I naively thought GitHub had some magic here since I didn't see a tag `v1` in the GitHub UI.

But yes pushing the tag tag as you have there makes sense.

**Comment by mattgauntseo-sentry** [comment]
Branch has been updates: https://github.com/getsentry/action-release/releases/tag/v1

PR is out to update release instructions so the next release will, hopefully, happen at the same time as the release.

**Comment by jcarvalho** [comment]
Awesome, can confirm the new version is being picked up! Thanks for fixing this.

I see you linked the PR to this issue, so will leave it open until the PR gets merged.

**Comment by chillyistkult** [comment]
It broke for me after being stable for the past 3 years any idea what's wrong?

```
- name: Create sentry release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: swaarm
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          RELEASE_VERSION: ${{ format('{0}-{1}', secrets.SENTRY_PROJECT, env.VERSION) }}
        with:
          environment: production
          sourcemaps: build
          version: ${{ format('{0}-{1}', secrets.SENTRY_PROJECT, env.VERSION) }}
```

<img width="1027" alt="Bildschirmfoto 2022-11-09 um 11 43 10" src="https://user-images.githubusercontent.com/1689047/200809760-db75765e-ac13-42f4-8d33-c4589e6f87c6.png">
