### ISSUE TITLE
checkout action deletes workspace files

### ISSUE THREAD

**Issue by jtgi** [getsentry/action-release#124]
# Github Sentry Action Release Bug Report

If you use the recommended flow in [sentry github action docs](https://github.com/marketplace/actions/sentry-release#usage), the checkout command will delete the workspace files. In my case this broke ability to reference source map in `action-release` thereafter.

## Environment

How do you use this action?
```
- uses: actions/checkout@v2
- name: Create Sentry release
  uses: getsentry/action-release@v1
  env:
    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
    SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  with:
    environment: production
    sourcemaps: './build/static/js'
```

Standard Github runners or self-hosted runners (which OS and arch?)
standard github runner

Which version of the action?
v2

## Steps to Reproduce
1. use the workflow above
2. try to resolve a source map in your ./dist ./build or w/e

## Expected Result
source map uploaded to sentry

## Actual Result
file i/o error cannot locate ./build.

What actually happened. Maybe a screenshot/recording? Maybe some logs?
The checkout action deletes the workspace and so the ./build directory cannot be found. Removing the checkout action resolves the issue.
