### ISSUE TITLE
No commits found. Change commits range, initial depth or use --ignore-empty to allow empty patch sets.

### ISSUE THREAD

**Issue by garrettg123** [getsentry/action-release#136]
# Github Sentry Action Release Bug Report

## Environment

How do you use this action?
standard

Which version of the action?
v1

## Steps to Reproduce

```
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: myorg
          SENTRY_PROJECT: myproj
          # SENTRY_URL: https://sentry.io/
        with:
          environment: production
```

## Expected Result

Sentry release success

## Actual Result

No commits found. Change commits range, initial depth or use --ignore-empty to allow empty patch sets.
