### ISSUE TITLE
Wrong commit selection

### ISSUE THREAD

**Issue by MaximeLaurenty** [getsentry/action-release#139]
# Github Sentry Action Release Bug Report

## Environment

How do you use this action?
Standard Github runners, container built on top of archlinux:base

Which version of the action?
getsentry/action-release@v1.3.1

## Steps to Reproduce

1. Setup action in our CI, triggered on every commit to master
```
- name: Create Sentry release
  uses: getsentry/action-release@v1.3.1
  env:
    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  with:
    environment: prod
    projects: frontend
    sourcemaps: frontend
    version: ${{ github.sha }}
    dist: ${{ github.sha }}
    url_prefix: "~"
```
2. Make multiples commits to master
3. Check info about releases into Sentry 

## Expected Result

Have only 1 commit in every release.

## Actual Result

Most of the time, commits are properly set within releases (just 1), but sometimes a discrepancy happens and a release contains multiple commits (for which releases already exist): 
see here commits in the latest release (including previous fe51918):
![Screenshot 2023-04-07 at 15 36 02 - sentry commit list](https://user-images.githubusercontent.com/13254296/230618739-ca4b3399-0689-46e2-af25-a98550f95eb1.png)
see here the release just before (which includes fe51918):
![Screenshot 2023-04-07 at 15 40 31 sentry release list](https://user-images.githubusercontent.com/13254296/230618753-c5832a2c-24c8-4f98-83fd-9080cafdb7ee.png)
links to sentry if you have access: [erroneous release](https://spinergie.sentry.io/releases/eb1fda568cb70ba9d3771bf730e87eb0ea5f55d1/commits/?project=4504916833796096), [right release before that](https://spinergie.sentry.io/releases/fe51918951f5c6e183be225a482985fd89e25d87/commits/?project=4504916833796096) & [list of our releases](https://spinergie.sentry.io/releases/?end=2023-04-07T11%3A59%3A59&project=4504916440252416&query=&start=2023-04-07T11%3A00%3A00&utc=true)
There is no relevant info in the logs of the action.
