### ISSUE TITLE
Github action warning

### ISSUE THREAD

**Issue by themyth92** [getsentry/action-release#14]
Hi, when I use this action on Production, there is a warning from this module.
The warning from Github is:
```
Unexpected input(s) 'version', valid inputs are ['entryPoint', 'args', 'environment', 'sourcemaps', 'finalize', 'started_at']
```

I believe it is because of the `version` input from the yml file.
My yml file is
```
# master.yml
...
- uses: getsentry/action-release@v1.0.0
  with:
      environment: production
      sourcemaps: './dist'
      version: 1.1.1
```

The release recorded from Sentry is correct and reflect the correct version from the yml file so It is not a big issue.
