### ISSUE TITLE
"Sentry not part of build pipeline" when using action for source maps

### ISSUE THREAD

**Issue by codybswaney** [getsentry/action-release#164]
# Github Sentry Action Release Bug Report

Hello, I'm trying to understand why sentry is saying "Sentry not part of build pipeline" when using this to create a release and upload source maps. Admittedly, our situation is specific in that we need to upload source maps without deploying the maps themselves to our production environment. Perhaps there is a better way to go here? 

Appreciate any help you can provide!

## Environment

Standard GitHub runners on ubuntu-latest, using `v1` action 

## Steps to Reproduce

1. Generate source maps
2. Inject debugIds via `sentry-cli sourcemaps inject out/_next/static`
3. Use action to create release and upload source maps
```yaml
            - name: Create Sentry Release
              uses: getsentry/action-release@v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
              with:
                  environment: staging
                  finalize: false
                  sourcemaps: ./out/_next/static
                  version: ${{ env.COMMIT_SHA_SHORT }}
``` 
4. Remove sourcemaps before production deploy
5. Production deploy initializes sentry and finalizes the release

## Expected Result

Viewing errors would un-minify the javascript.

## Actual Result

> Sentry not part of build pipeline
> [Read Guide](https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/#uploading-source-maps-to-sentry)
Integrate Sentry into your build pipeline using a tool like Webpack or the CLI.

<img width="2384" alt="Screenshot 2023-07-19 at 4 21 40 PM" src="https://github.com/getsentry/action-release/assets/15198961/5b8d61ac-5c6b-49fc-a70d-9fef56b4aa19">

I can see the artifacts associated with the release in sentry as well
<img width="349" alt="Screenshot 2023-07-19 at 4 24 55 PM" src="https://github.com/getsentry/action-release/assets/15198961/cda10dd5-f52e-4aee-b811-610f439eab5c">
