### ISSUE TITLE
Workflow environment variables are ignored

### ISSUE THREAD

**Issue by lewislbr** [getsentry/action-release#166]
# Github Sentry Action Release Bug Report

## Environment

Standard Github runners on Ubuntu

Action version v1

## Steps to Reproduce

The action does not read workflow environment variables.

Given the simplified workflow:

```
name: Release foo

on:
  push:
    branches: [main]

env:
  PROJECT_NAME: foo

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
          SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
          SENTRY_PROJECT: "$PROJECT_NAME"
        with:
          environment: production
          ignore_empty: true
          ignore_missing: true
```

## Expected Result

`SENTRY_PROJECT` to be `foo`.

## Actual Result

Got the following error instead: `Command failed: /action-release/dist/sentry-cli releases new a7d3ba5 -p $PROJECT_NAME error: project not found`.

It would be great to be able to reuse existing variables in order to avoid duplication, and having to store secrets for things that are not really secrets. Same for the environment property, which needs to be hardcoded.
