### ISSUE TITLE
Could not automatically determine release name

### ISSUE THREAD

**Issue by sujanbasnet1** [getsentry/action-release#187]
# Github Sentry Action Release Bug Report

## Environment
sentry-cli version: 2.24.1
platform: "linux"
architecture: "x86_64"

How do you use this action?
Self hosted runner - linux

Which version of the action?
v1

## Steps to Reproduce
```
jobs:
  sentry-release:
    name: Sentry release

    runs-on:
      [self-hosted, linux, x64]
      
    steps:
      - name: Chown user
        # if: contains('Github', vars.RUNNER_NAME) == false
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Git status
        run: git status

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: "organization"
          SENTRY_PROJECT: "project"
          SENTRY_LOG_LEVEL: "debug"
        with:
          sourcemaps: "./.next"
          environment: "staging"
```

## Expected Result

Should create a release.

## Actual Result

```
Error: Command failed: /action-release/node_modules/@sentry/cli-linux-x64/bin/sentry-cli releases propose-version
  DEBUG   2024-02-28 05:19:24.704325762 +00:00 sentry-cli version: 2.24.1, platform: "linux", architecture: "x86_64"
  INFO    2024-02-28 05:19:24.707921124 +00:00 sentry-cli was invoked with the following command line: "/action-release/node_modules/@sentry/cli-linux-x64/bin/sentry-cli" "releases" "propose-version"
error: Could not automatically determine release name:
	 unsupported extension name extensions.worktreeconfig; class=Repository (6) 

Please ensure your version control system is configured correctly, or provide a release name manually.
  DEBUG   2024-02-28 05:19:24.714110727 +00:00 skipping update nagger because session is not attended
```

Screenshots of some steps

<img width="1077" alt="image" src="https://github.com/getsentry/action-release/assets/85692779/e387d99e-1e00-4d81-9419-29729aa6abf6">

**Comment by mbaranavaya** [comment]
@sujanbasnet1 I had the same issue. In my case, the problem was with `sparse-checkout`  which was in other job (in other pipeline).

**Comment by sujanbasnet1** [comment]
@mbaranavaya Thanks for the response. We don't explicitly set `sparse-checkout` in any job.

**Comment by Sharpek** [comment]
@sujanbasnet1 the problem is with `extensions.worktreeconfig` set by `actions/checkout@v4`. 

You can fix this by doing something like this:

```
      - name: Change git configuration
        shell: bash
        run: git config --unset-all extensions.worktreeconfig
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: staging
      - name: Rollback git configuration
        shell: bash
        run: git config extensions.worktreeconfig true
```

In my case it fix this issue.
