### ISSUE TITLE
Creating deployment

### ISSUE THREAD

**Issue by ziggy6792** [getsentry/action-release#194]
If my release already exists and I just want to record a deployment should I use this?

It seems this may replace the release I want to record a deployment for?

I see that when releases are created from my dev environment loose information (like: git contributors) when I use the action to record a deployment to a new env (e.g: when my dev release goes to prod). 

```
      - name: Create Sentry Deployment
        id: create-sentry-deployment
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: <TARGET ENVIRONMENT>
          version: <SOME PRE-EXISTING RELEASE VERSION>
```
