### ISSUE TITLE
NPM not available on all runners

### ISSUE THREAD

**Issue by bswinnerton** [getsentry/action-release#253]
# Github Sentry Action Release Bug Report

## Environment

**How do you use this action?**
Self hosted runners with [this](https://github.com/myoung34/docker-github-actions-runner) Docker image

**Which version of the action?**
v1

## Problem

Using the latest version of this Action on any self-hosted runner that lacks NPM results in a failure:

```
Run getsentry/action-release@v1
  with:
    environment: staging
    projects: backend frontend
    finalize: true
  env:
    SENTRY_AUTH_TOKEN: ***
    SENTRY_ORG: ***
Run npm install --save-dev --no-package-lock @sentry/cli@^2.4
  npm install --save-dev --no-package-lock @sentry/cli@^2.4
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SENTRY_AUTH_TOKEN: ***
    SENTRY_ORG: ***
/tmp/runner/work/_temp/9b196bcc-f2cc-4ecf-9b64-549f6debc295.sh: line 1: npm: command not found
```

This is because my runner was previously configured to use Yarn, but as of https://github.com/getsentry/action-release/pull/251, is now broken. While I could install NPM before using the Sentry action, I think it might make sense to consider having this action check for the presence of a package manager like NPM, and if one does not exist, install it before invoking the sentry CLI install command.

---

cc https://github.com/getsentry/action-release/issues/247
