### ISSUE TITLE
Wrong commit selection

### ISSUE THREAD

**Issue by MaximeLaurenty** [getsentry/action-release#276]
# Github Sentry Action Release Bug Report
This is a followup of https://github.com/getsentry/action-release/issues/139 given @andreiborza's [last comment](https://github.com/getsentry/action-release/issues/139#issuecomment-2731963509) and given the issue persists.

## Environment

How do you use this action?
Standard Github runners, container built on top of archlinux:base

Which version of the action?
getsentry/action-release@v3.1.0

## Steps to Reproduce

1. Setup action in our CI, triggered on every commit to master
```
      - name: Create Sentry release
        uses: getsentry/action-release@fa247637f74d407f51d8423a5dc10abae1917873 # v3.1.0 # https://github.com/getsentry/action-release/tags
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
        with:
          environment: prod
          projects: js-angular spindjango php-symfony
          sourcemaps: web
          release: ${{ github.sha }}
          dist: ${{ github.sha }}
          url_prefix: "~"
```

2. Make multiples commits to master
3. Check info about releases into Sentry

## Expected Result

Have only 1 commit in every release.

## Actual Result

Most of the time, commits are properly set within releases (just 1), but sometimes a discrepancy happens and a release contains multiple commits (for which releases already exist):
see here commits in the latest release (including previous bd4b346):
![Image](https://github.com/user-attachments/assets/6fc7b16b-437f-40f0-ad8c-34f6885a6a11)

see here the release just before (which includes bd4b346 and only it):
![Image](https://github.com/user-attachments/assets/fe54b832-0f17-44e5-9842-477a5eca368f)

![Image](https://github.com/user-attachments/assets/e7efe118-61c7-4c52-8ab2-c6461635e606)

links to sentry if you have access: [erroneous release](https://spinergie.sentry.io/releases/c715289498095904d1b0012fb50292843f57a173/commits/?project=4504916833796096), [right release before that](https://spinergie.sentry.io/releases/bd4b3467f9f741fbf01e5fb8e6a52f5bd4c0626e/commits/?project=4504916833796096) & [list of our releases](https://spinergie.sentry.io/releases/?end=2025-03-19T22%3A59%3A59&project=4504916833796096&start=2025-03-19T10%3A20%3A00)
logs with actions debugging enabled (after obfuscation of RUNS_ON related information + removed most of the frontend files): 
[GHA_logs_sentry.txt](https://github.com/user-attachments/files/19339277/GHA_logs_sentry.txt)

**Comment by andreiborza** [comment]
Hi @MaximeLaurenty, thanks for filing this as a new issue.

Have you found possible patterns for when this might happen? For example, does this happen if commits to master are quickly one after another?

**Comment by MaximeLaurenty** [comment]
After re-looking trough it, I found a pattern: sentry releases are using the full sha but we use a short sha in our backend code, so sentry creates new releases (for the backend projects but not for the frontend projects) for the short sha as soon as a request is spotted.
- When a release is created with the CLI / CI after a release created with the CLI / CI it's working fine,
- When a release is created with the CLI / CI after a release created with the short sha (which includes no commit), the issue happens and the release has a history of 20 commits.

![Image](https://github.com/user-attachments/assets/9de8c4f6-a3cb-420d-96e2-b5272c38baec)

After aligning releases & frontend code to use the short sha, this issue is not present anymore.

However another issue happens: source-map un-minification is not working anymore ... but I guess that's another topic.

**Comment by MaximeLaurenty** [comment]
@andreiborza Merging in our private repo a PR mentioning this issue closed it (weirdly), I'm not sure the issue should be closed though: the inference of commits when creating a release could be based on the latest 5-10 releases instead of just the last one.

**Comment by RomeoAva** [comment]
Hi,

I am also facing this same issue. I just started using Sentry and wanted to connect this action to my private Github project.

In my project the action is triggered in twice:

- Once when PR is merged onto `main` for the `development` environment.
- Once when `main` is `released` for the `production` environment.

Here is my workflow:

```
name: Sentry Release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: development | production

jobs:
  sentry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ inputs.environment }}
          release: ${{ github.sha }}
          dist: ${{ github.sha }}
```


But the issue is every time a release happens (no matter if its dev/prod), the Sentry UI is displaying the Commits & Files Changed.

I am not sure if I am doing something wrong..


Latest release:
![Image](https://github.com/user-attachments/assets/7b85ce86-4c7b-487f-ab49-3e34f61237b3)

The one before:
![Image](https://github.com/user-attachments/assets/2759b21a-412b-418a-abca-3f14383bb43b)

And same for the previous ones (won't screenshot every single one)

And realistically, between those releases only 1 file/commit was changed.

Also to note compared to this original issue, my application is solely backend (FastAPI App).

Thank you

**Comment by RomeoAva** [comment]
I think the issue might be caused by:

```
       with:
          fetch-depth: 0
```

I am following the documentation: https://github.com/getsentry/action-release?tab=readme-ov-file#usage

**Comment by panthony** [comment]
Using action-release@v3 I have the same problem. Always 20 commits even when there are only 1 or 2 expected.

The flow is triggered when a tag is published only:

```yaml
on:
  push:
    tags:
      - '*'
```

Using like this:

```yaml
      - name: Create Sentry Release
        uses: getsentry/action-release@v3
        env:
          SENTRY_ORG: xx
          SENTRY_PROJECT: xx
          SENTRY_AUTH_TOKEN: xx
        with:
          environment: production
          release: ${{ env.APP_VERSION }}
          sourcemaps: dist/production
```
