### ISSUE TITLE
The action is modifying the runner node configuration permanently

### ISSUE THREAD

**Issue by grzegorzkrukowski** [getsentry/action-release#279]
### Environment

We added this action to our release process, but it breaks all subsequent steps due to setup-node being called with a different version than required in our release process.

After the action completes, I would expect it doesn't permanently modify my runner node version for all other actions.

### Version

v3

### Steps to Reproduce

```
- name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"
      - name: Print Node Version (Before)
        run: node --version //22.16.0
      - name: Upload Sourcemaps to Sentry
        uses: getsentry/action-release@v3
        with:
          environment: Internal
          sourcemaps: "./dir/"
      - name: Print Node Version (After)
        run: node --version //18.17.0
```

### Expected Result

After action completion, the Node version should still be 22.16.0 for all other actions

### Actual Result

The Node version is downgraded to 18.17 instead and all actions called after the upload are failing
