### ISSUE TITLE
Is it possible to set custom Sentry URL?

### ISSUE THREAD

**Issue by Trimud** [getsentry/action-release#28]
Hello,

is it possible to set custom URL for on-perm instances of Sentry or this action will always connect to sentry.io?

Thanks

**Comment by d-moos** [comment]
Since this actions uses the @sentry/cli, it should be sufficient to set the SENTRY_URL env variable in your yaml file.

```
 - name: Create Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_URL: https://sentry.myurl.com/
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: xxxx
          SENTRY_PROJECT: xxxx
```
