### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by temp** [getsentry/action-release#281]
### Environment

Is there a way to configure the verbosity of the output of the action?
Right now it is completely empty (for me). I'd like to see a summary of what was created.
Or am I missing something?

### Version

v3

### Steps to Reproduce

```
      - name: Create Sentry release
        if: steps.semantic.outputs.new_release_version
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
```

### Expected Result

<some output>

### Actual Result

<img width="1079" alt="Image" src="https://github.com/user-attachments/assets/9e984c8b-7db6-4feb-b706-403cbef3b064" />
