### ISSUE TITLE
Sentry project accepts multiple args

### ISSUE THREAD

**Issue by LeoFalco** [getsentry/action-release#29]
I have a workflow on github actions that publishes several modules from a repository
(monorepo)

it would be interesting if I could release the multiple modules (which are projects in sentry) in one step
via `SENTRY_PROJECT`accepting multiple args

something like this
```yml
  - name: Create Sentry release
    uses: getsentry/action-release@v1
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_PROJECT: orodruin-worker orodruin-server
    with:
      environment: production
      version: ${{ needs.changelog.outputs.ref }}
```
