### ISSUE TITLE
version_prefix ignored when version provided

### ISSUE THREAD

**Issue by pbstriker38** [getsentry/action-release#34]
The `getVersion()` function prematurely returns when the version option is set.

So, something like this ignores the prefix option
```
- name: Create Sentry Release
  uses: getsentry/action-release@v1
  with:
    environment: prod
    version_prefix: app-name@
    version: ${{ env.IMAGE_TAG }}
```
