### ISSUE TITLE
Unexpected input 'url_prefix'

### ISSUE THREAD

**Issue by ericgrigorian** [getsentry/action-release#37]
I'm trying to create a Sentry.io release using the Github action and keep running into the error below:
```
Warning: Unexpected input(s) 'url_prefix', valid inputs are ['entryPoint', 'args', 'environment', 'sourcemaps', 'finalize', 'started_at', 'version', 'version_prefix', 'set_commits', 'projects']
Run getsentry/action-release@v1
/usr/bin/docker run --name sentryintegrationssentrygithubactionreleaselatest_d37d34 --label 179394 --workdir /github/workspace --rm -e SENTRY_AUTH_TOKEN -e SENTRY_ORG -e SENTRY_PROJECT -e INPUT_ENVIRONMENT -e INPUT_SOURCEMAPS -e INPUT_URL_PREFIX -e INPUT_FINALIZE -e INPUT_STARTED_AT -e INPUT_VERSION -e INPUT_VERSION_PREFIX -e INPUT_SET_COMMITS -e INPUT_PROJECTS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/oneasics-portal/oneasics-portal":"/github/workspace" sentryintegrations/sentry-github-action-release:latest
```
The relevant part of my yaml file:
```
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: 'dev2'
          set_commits: 'skip'
          sourcemaps: './build/static/js'
          url_prefix: '~/console/static/js'
```
Should I be using `entryPoint` instead of `url_prefix`?

**Comment by scefali** [comment]
@ericgrigorian That's odd. `url_prefix` should be a valid option. Here's why my yml file looks like:

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Sentry Release
      uses: getsentry/action-release@v1 # Change the version for testing
      with:
        environment: production
        url_prefix: ~/static/js
        sourcemaps: build/static/js
```

Just tested and it works fine for me. I don't know why it's not working for you though.

**Comment by ericgrigorian** [comment]
@scefali agreed. I just tried changing `getsentry/action-release@v1` to `getsentry/action-release@v1.1.3` to set the latest version explicitly and that worked for some reason. The action runner still threw a warning but the step completed successfully 🤷‍♂️ . Thanks for looking into this though. I'll just close the issue.

Output below in case you need it to investigate further:

```
Warning: Unexpected input(s) 'url_prefix', valid inputs are ['entryPoint', 'args', 'environment', 'sourcemaps', 'finalize', 'started_at', 'version', 'version_prefix', 'set_commits', 'projects']
Run getsentry/action-release@v1.1.3
/usr/bin/docker run --name sentryintegrationssentrygithubactionreleaselatest_094d68 --label 179394 --workdir /github/workspace --rm -e SENTRY_AUTH_TOKEN -e SENTRY_ORG -e SENTRY_PROJECT -e REACT_APP_VERSION -e INPUT_ENVIRONMENT -e INPUT_SET_COMMITS -e INPUT_SOURCEMAPS -e INPUT_URL_PREFIX -e INPUT_FINALIZE -e INPUT_STARTED_AT -e INPUT_VERSION -e INPUT_VERSION_PREFIX -e INPUT_PROJECTS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/oneasics-portal/oneasics-portal":"/github/workspace" sentryintegrations/sentry-github-action-release:latest
> Found 36 release files
> Analyzing 36 sources
> Rewriting sources
> Adding source map references
> Bundled 36 files for upload
> Uploaded release files to Sentry
> File upload complete

Source Map Upload Report
  Minified Scripts
    ~/console/static/js/0.ac4c7fa9.chunk.js (sourcemap at 0.ac4c7fa9.chunk.js.map)
    ~/console/static/js/1.cc6cbe5b.chunk.js (sourcemap at 1.cc6cbe5b.chunk.js.map)
    ~/console/static/js/10.d94294bf.chunk.js (sourcemap at 10.d94294bf.chunk.js.map)
    ~/console/static/js/11.ee55fa4f.chunk.js (sourcemap at 11.ee55fa4f.chunk.js.map)
    ~/console/static/js/12.c84de846.chunk.js (sourcemap at 12.c84de846.chunk.js.map)
    ~/console/static/js/13.feb943d5.chunk.js (sourcemap at 13.feb943d5.chunk.js.map)
    ~/console/static/js/14.95207f9d.chunk.js (sourcemap at 14.95207f9d.chunk.js.map)
    ~/console/static/js/15.835a1110.chunk.js (sourcemap at 15.835a1110.chunk.js.map)
    ~/console/static/js/16.546f0036.chunk.js (sourcemap at 16.546f0036.chunk.js.map)
    ~/console/static/js/17.cffbdcc3.chunk.js (sourcemap at 17.cffbdcc3.chunk.js.map)
    ~/console/static/js/2.982cd050.chunk.js (sourcemap at 2.982cd050.chunk.js.map)
    ~/console/static/js/3.f75f97b1.chunk.js (sourcemap at 3.f75f97b1.chunk.js.map)
    ~/console/static/js/4.e8e8a013.chunk.js (sourcemap at 4.e8e8a013.chunk.js.map)
    ~/console/static/js/7.2b6e1478.chunk.js (sourcemap at 7.2b6e1478.chunk.js.map)
    ~/console/static/js/8.8d21bae7.chunk.js (sourcemap at 8.8d21bae7.chunk.js.map)
    ~/console/static/js/9.28afb064.chunk.js (sourcemap at 9.28afb064.chunk.js.map)
    ~/console/static/js/main.71c68d20.chunk.js (sourcemap at main.71c68d20.chunk.js.map)
    ~/console/static/js/runtime-main.7df6b68a.js (sourcemap at runtime-main.7df6b68a.js.map)
  Source Maps
    ~/console/static/js/0.ac4c7fa9.chunk.js.map
    ~/console/static/js/1.cc6cbe5b.chunk.js.map
    ~/console/static/js/10.d94294bf.chunk.js.map
    ~/console/static/js/11.ee55fa4f.chunk.js.map
    ~/console/static/js/12.c84de846.chunk.js.map
    ~/console/static/js/13.feb943d5.chunk.js.map
    ~/console/static/js/14.95207f9d.chunk.js.map
    ~/console/static/js/15.835a1110.chunk.js.map
    ~/console/static/js/16.546f0036.chunk.js.map
    ~/console/static/js/17.cffbdcc3.chunk.js.map
    ~/console/static/js/2.982cd050.chunk.js.map
    ~/console/static/js/3.f75f97b1.chunk.js.map
    ~/console/static/js/4.e8e8a013.chunk.js.map
    ~/console/static/js/7.2b6e1478.chunk.js.map
    ~/console/static/js/8.8d21bae7.chunk.js.map
    ~/console/static/js/9.28afb064.chunk.js.map
    ~/console/static/js/main.71c68d20.chunk.js.map
    ~/console/static/js/runtime-main.7df6b68a.js.map
```
and my yml file:
```
jobs:
  builds:
    name: Build and Deploy sourcemaps to Sentry.io
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      REACT_APP_VERSION: ${{ github.sha }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install --only=prod
      - name: Prod build
        run: npm run build
      - name: Create Sentry release
        uses: getsentry/action-release@v1.1.3
        with:
          environment: 'Dev2'
          set_commits: 'skip'
          sourcemaps: './build/static/js'
          url_prefix: '~/console/static/js'
```
