### ISSUE TITLE
Could not find the SHA of the previous release

### ISSUE THREAD

**Issue by epicserve** [getsentry/action-release#41]
When I used the following:

```
sentry_release:
  name: Create Sentry release
  needs: [ test_js, test_py ]
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/master'
  steps:
    - uses: actions/checkout@v2
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ env.ORG }}
        SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
      with:
        environment: prod
```

I got the following error:
```
error: Could not find the SHA of the previous release in the git history. Increase your git clone depth.
```

It wasn't clear obvious what to do right away, so I'm wondering if, in the documentation/README, it would be better to change the checkout step to following and add a note about why it's necessary.
```
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

This is what solved it for me. I also wasn't sure if I should use something other than zero because in Github's docs it's not clear what other numbers do.

I'm happy to make a PR for the README if this sounds good or please go ahead and just change it if you want.

Thank you!

**Comment by peterjgrainger** [comment]
Pretty sure this is the same issue https://github.com/getsentry/sentry-cli/issues/792

**Comment by peterjgrainger** [comment]
Actually my issue was I didn't have the Sentry <-> GitHub integration configured correctly

**Comment by mhihasan** [comment]
Hi, I am getting the same error even after adding `fetch-depth: 0`. Any solution?

``` yml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
- name: Create Sentry release
  uses: getsentry/action-release@v1
  env:
    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
    SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  with:
    environment: production
```

**Comment by pierresaad** [comment]
Same here getting the same error even after adding fetch-depth: 0

**Comment by gilles-yvetot** [comment]
@mgaeta @scefali Unfortunately it looks like `fetch-depth: 0` is not solving the problem :( Any input on that?

**Comment by abecks** [comment]
Can confirm `fetch-depth: 0` is no longer resolving `error: Could not find the SHA of the previous release in the git history. Increase your git clone depth.`

**Comment by localheinz** [comment]
What can we do to help move this issue forward?

**Comment by mhihasan** [comment]
My problem was actually elsewhere. I needed to add the integration between repository and sentry.

**Comment by qua11q7** [comment]
My integration was working perfectly between Sentry and repository perfectly, but after I hard reset a commit, sentry started to give this error. Setting `fetch-depth: 0` didn't fix the issue. If it would help, the order of operations I did as follows:

1. At the initial state, let's call the current hash of the commit `hash0`. Sentry correctly shows this as a release.
2. I pushed a commit to branch and it triggered the sentry GitHub Action, this release worked fine. Let's call this hash `hash1`
3. I hard reset the commit to the previous commit `hash0` and force pushed it to the branch. This also triggered the GitHub action. Sentry gave the following error: `Command failed: /action-release/dist/sentry-cli releases set-commits hash0 --auto error: No commits found. Leaving release alone.`
4. I pushed another commit to the branch with hash `hash2`. This time Sentry gave the following error: `Command failed: /action-release/dist/sentry-cli releases set-commits hash2 --auto error: Could not find the SHA of the previous release in the git history.`
5. I have altered the GitHub Action to include `fetch-depth: 0` and pushed it. The same error is given in the workflow for the new commit hash.

I have tried to delete the release for the faulty `hash1` from Sentry, as it no longer exists in GitHub commit history. I couldn't find a way of deleting from Sentry and only archived the release. It didn't solve the problem. Any help is appreciated.

**Comment by gilles-yvetot** [comment]
I don't think this repo is maintained anymore

**Comment by drummerjolev** [comment]
Having the same error, shame this is no longer maintained

**Comment by NisanthanNanthakumar** [comment]
Hi everyone! I need some more info to help debug this issue for y'all.
@mhihasan did your project have a release from another repo before you setup this action?
@qua11q7 yes it sounds like the cli is trying to find `hash1` in your git tree bc the last found release ended with `hash1`. I am not sure if you can delete a release in the Sentry UI without the proper auth role. 
You can use our API to delete: https://docs.sentry.io/api/releases/delete-an-organizations-release/

**Comment by Fredx87** [comment]
I have the same issue, I created a release from a feature branch, then squashed the commits, and then the merge to master created a new release. The release creation on master fails with `Could not find the SHA of the previous release in the git history.`.

This case is mentioned in the documentation: https://docs.sentry.io/product/cli/releases/#dealing-with-missing-commits. Probably it would be nice to add the `ignore-missing` flag to the parameters of the action.

**Comment by drummerjolev** [comment]
@NisanthanNanthakumar could you add the `ignore-missing` flag?

**Comment by tazik561** [comment]
when I am using 
 flutter packages pub run sentry_dart_plugin  --ignore-missing
after building with --source-map 
still I got error: 

☑ uploading source maps                                                             

Could not determine any commits to be associated with a repo-based integration. Proceeding to find commits from local git tree.

error: Could not find the SHA of the previous release in the git history. If you limit the clone depth, try to increase it. Otherwise, it means that the commit we are looking for was amended or squashed and cannot be retrieved. Use --ignore-missing flag to skip it and create a new release with the default commits count.

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

exitCode: 1


my project yml file:


```
dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^7.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  sentry_dart_plugin: ^1.0.0

sentry:
  upload_debug_symbols: false
  upload_source_maps: true
  upload_sources: false
  project: my_project_name
  org: myorg
  auth_token: a9.....287
  log_level: error
  commits: auto
```
