### ISSUE TITLE
Command failed: /action-release/dist/sentry-cli releases set-commits 2.5 --auto

### ISSUE THREAD

**Issue by chadfaurie** [getsentry/action-release#42]
I am using Sentry Saas
This error comes from the github action

I have setup the action as follows:
```
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: $ENVIRONMENT
          sourcemaps: ./build
          version: ${{ env.REACT_APP_BUILD_NUMBER }}
          set_commits: auto
```

I then get the error:
`Command failed: /action-release/dist/sentry-cli releases set-commits 2.5 --auto`

` 2.5` is the value of REACT_APP_BUILD_NUMBER in this run,
