### ISSUE TITLE
Unexpected input(s) 'version_prefix'

### ISSUE THREAD

**Issue by snasirca** [getsentry/action-release#49]
### Environment

How do you use Sentry?

Sentry SaaS (sentry.io)

Which SDK and version?

```
gem "sentry-rails", "4.3.2"
gem "sentry-ruby", "4.3.1"
```

### Steps to Reproduce

1. Set up Sentry Release GitHub Action with this:
```
name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
      - name: Notify Sentry of Build
        uses: getsentry/action-release@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: nulogy
          SENTRY_PROJECT: opscore
        with:
          version_prefix: opscore@
```
2. Trigger GitHub Action by pushing to `main`

### Expected Result

No warnings

### Actual Result

Warning message in the GitHub Action: ![image](https://user-images.githubusercontent.com/1246295/113005307-5bdcd400-9142-11eb-8fc6-ec933ec2e1cd.png)

The version prefix seems to be getting through though because I see it in the Releases page in Sentry: 
![image](https://user-images.githubusercontent.com/1246295/113028367-2f808200-9159-11eb-940d-1af8adcf1a4d.png)
