### ISSUE TITLE
error: API request failed (http status: 403)

### ISSUE THREAD

**Issue by Sophie-run** [getsentry/action-release#51]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
N/A

### Steps to Reproduce

1. I added code below in my workflow and wanted to upload my source maps to Sentry:
```
 - name: Sentry Release
        uses: getsentry/action-release@v1.1.5
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: HIDDEN
          SENTRY_PROJECT: HIDDEN
        with:
          environment: prod
          sourcemaps: dist
          set_commits: skip
```
And below are my permissions:
<img width="1168" alt="Screenshot 2021-04-07 at 0 25 53" src="https://user-images.githubusercontent.com/76094427/113736181-d8217980-9737-11eb-9988-b035c4d2842a.png">

### Expected Result

Successfully create a new release to Sentry and upload the source maps.

### Actual Result

<img width="984" alt="Screenshot 2021-04-07 at 0 19 05" src="https://user-images.githubusercontent.com/76094427/113735859-97296500-9737-11eb-9e57-76170b9a8cf0.png">
