### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by alekhinen** [getsentry/action-release#58]
Hello! I'm porting over my team's react native build pipeline from CircleCI to Github Actions and just discovered that this action is only supported on Linux containers. 

<img width="502" alt="Screen Shot 2021-05-28 at 10 05 51 AM" src="https://user-images.githubusercontent.com/2717795/120006796-dd17e200-bf9e-11eb-8352-2cb80f6781f1.png">

As a workaround, we're going to have to install `sentry-cli` and run the release command manually. It would be great to have this action work on `macos` as well!

**Comment by xt0rted** [comment]
Just set this up only to hit the same issue since I'm running on a Windows vm. To work around this I'm writing my version to a text file that gets uploaded as a build artifact, then in a second job I download that file, read the version out, and then create the release with it.

```yaml
jobs:
  build:

      # ...

      - name: Write version
        run: |
          "${{ steps.build.outputs.version }}" > ./artifacts/version.txt
        shell: pwsh

      - name: Upload release version
        uses: actions/upload-artifact@v2.2.4
        with:
          name: version
          path: artifacts/version.txt

      # ...

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4

      - name: Download release version
        uses: actions/download-artifact@v2.0.10
        with:
          name: version

      - name: Get release version
        id: meta
        run: |
          _version="$(cat ./version.txt)"
          echo "::set-output name=version::${_version}"

      - name: Create Sentry release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        with:
          environment: production
          projects: ${{ secrets.SENTRY_PROJECT }}
          version: ${{ steps.meta.outputs.version }}
```
