### ISSUE TITLE
Ability to add multiple environments

### ISSUE THREAD

**Issue by khalilgharbaoui** [getsentry/action-release#62]
Currently, It's possible to optionally add a single environment.

```
- uses: actions/checkout@v2
- name: Create Sentry release
  uses: getsentry/action-release@v1
  env:
     . . .
  with:
    environment: production  #<<<
```

It would be great to be able to add multiple environments for example:
```
  with:
    environments: [production, staging]
```
Or:
  with:
    environments:
     - production
     - staging
     - ...
```

The only way to achieve this kind of behavior now is to have it all twice which is a pain especially if your deploy is actually a build of a docker image with a push to a registry only.
