### ISSUE TITLE
can not get any sourcemap files when i had set sourcemaps

### ISSUE THREAD

**Issue by weirui88888** [getsentry/action-release#73]
### below is my action

```
 - name: Send Release To Sentry
    uses: getsentry/action-release@v1
    env:
      SENTRY_AUTH_TOKEN: "xxx"
      SENTRY_ORG: "xxx"
      SENTRY_PROJECT: "xxx"
      SENTRY_URL: "xxx"
    with:
      environment: "production"
      sourcemaps: "./dist/assets"
      version: ${{ github.sha }}
      set_commits: "skip"
      url_prefix: "~/sentry-config-test/assets"
```

### Expected Result

i hope i can upload sourcemap successful!!!

### Actual Result

![image](https://user-images.githubusercontent.com/23164664/137875121-d0e24da7-dd4c-4d99-95b5-d6ec0bd66eb4.png)
