### ISSUE TITLE
Fail to include info about commits

### ISSUE THREAD

**Issue by duhlin** [getsentry/action-release#75]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
getsentry/action-release@v1

### Steps to Reproduce
I've followed the intructions to configure getsentry/action-release

1. I've declared an Internal Integration, with the appropriate permissions (Release - Admin, Organization - Read).
2. I've edited my github workflow to fetch all commits from all branches on checkout
```
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```
3. I've added to my github workflow a step:
```
     - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
```
3. My workflow is scheduled to be executed on commits on the release branch, I've then pushed a few commits.

### Expected Result

Release should be created in sentry.io and the related commits should be shown, i.e. the list of new commits, not included in the previous release.

### Actual Result

No commit information is shown on sentry.io
![image](https://user-images.githubusercontent.com/3609946/141771799-ccf6cb6b-f729-4960-b2f7-9df50adeaad7.png)

No log on github action side
![image](https://user-images.githubusercontent.com/3609946/141772475-1e70e0c7-0cdd-4743-aaad-9bf9f0d7d877.png)
