### ISSUE TITLE
Incorrect example of how to set the `version` parameter

### ISSUE THREAD

**Issue by AJenbo** [getsentry/action-release#79]
### Environment

https://github.com/marketplace/actions/sentry-release#examples

The given example is wrong:
```
- uses: getsentry/action-release@v1
  with:
    environment: 'production'
    version: 'v1.0.1'
```

### Steps to Reproduce

1. Use the given example

### Expected Result

Version is set to 'v1.0.1'

### Actual Result

`Warning: Unexpected input(s) 'version', valid inputs are ['entryPoint', 'args', 'environment', 'sourcemaps', 'finalize', 'started_at']`
