### ISSUE TITLE
Automatic version does not work if repo is checked out to a path other than Workspace

### ISSUE THREAD

**Issue by SandyRogers** [getsentry/action-release#83]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
`getsentry/action-release@v1.1.6`

### Steps to Reproduce

1. Create a GitHub Actions workflow that checks out repository to non-default path:2. 
```yaml
steps:
  - uses: actions/checkout@v3
     name: 🔬 - Checkout EMG API
     with:
       repository: 'someuser/somerepo'
       ref: 'abranch'
       path: 'a-subdir'

  - name: Sentry Release
     uses: getsentry/action-release@v1.1.6
     env:
       SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
       SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
       SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
     with:
       environment: 'an-env'
       sourcemaps: './a-subdir/dist/js'
```
### Expected Result

The version should be taken from the commit SHA.

### Actual Result
The action step fails:

```
Error: Command failed: /action-release/dist/sentry-cli releases propose-version
[28](https://github.com/<someuser>/<somerepo>/runs/<runid>?check_suite_focus=true#step:21:28)
error: Could not automatically determine release name
```

This is because the action does NOT use the GitHub SHA directly, but calls the CLI's `proposeVersion`, which seemingly needs to be run with the working-dir as the repository.

### Partial fix, second failure
Add `with: version: ${{ github.sha }}` to the Sentry Release action.

#### Expected Result
The manual version label is then used and action should succeed.

#### Actual Result
Action step fails:
```
INFO    2022-04-12 08:27:21.419745496 +00:00 Resolving HEAD (<someuser>/<somerepo>@HEAD)
error: could not find repository from '.'; class=Repository (6); code=NotFound (-3)
```
